apiVersion: apps/v1
kind: Deployment
metadata:
  name: devery
  labels:
    app: devery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devery
  template:
    metadata:
      labels:
        app: devery
    spec:
      containers:
        - name: devery
          image: username/devery:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
